### ISSUE TITLE
resolver execution order

### ISSUE THREAD

**Issue by tcisagebio** [lukeplausin/sceptre-template-resolver#1]
Would it be possible to add some docs on the execution order of your resolver?  I mean when does the script get executed relative to other things in sceptre like parameter resolvers, hooks, etc..?

**Comment by lukeplausin** [comment]
This behaviour is controlled by Sceptre itself and not by this custom template resolver. The order of resolution between parameters, hooks and resolvers by Sceptre also *_should_* not matter, as these items typically would be static during a deployment (unless you are using hooks to change the contents of some external inputs, or if there is something strange going on with custom resolvers).

**Comment by lukeplausin** [comment]
Since this behaviour is not controlled from within this custom resolver, I am going to to close the issue. It might be worth asking in the Sceptre project repository.

https://github.com/Sceptre/sceptre
